name: sophos_rag
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip>=21.0
  - numpy>=1.20.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - pytorch>=1.10.0
  - faiss-cpu>=1.7.0
  - pip:
    - transformers>=4.15.0
    - sentence-transformers>=2.2.0
    - chromadb>=0.4.0
    - openai>=1.0.0
    - langchain>=0.0.200
    - nltk>=3.6.0
    - spacy>=3.2.0
    - beautifulsoup4>=4.10.0
    - python-docx>=0.8.11
    - PyPDF2>=2.0.0
    - fastapi>=0.95.0
    - uvicorn>=0.15.0
    - pydantic>=1.9.0
    - tqdm>=4.62.0
    - pyyaml>=6.0
    - python-dotenv>=0.19.0