# Default configuration for Sophos RAG

# Data processing settings
data:
  chunk_size: 512
  chunk_overlap: 50
  text_splitter: "recursive"  # Options: recursive, sentence, token
  encoding: "utf-8"

# Embedding settings
embeddings:
  encoder_type: tfidf
  max_features: 1000
  ngram_range: [1, 2]  # 这个会被转换为元组

# Vector store settings
vector_store:
  type: faiss
  dimension: 1000  # TF-IDF 特征维度
  index_type: Flat
  distance_metric: cosine
  nprobe: 10

# Retriever settings
retriever:
  type: similarity
  top_k: 3
  score_threshold: 0.1

# Generator settings
generator:
  type: huggingface
  model_name: "facebook/opt-125m"
  device: "cpu"  # Use CPU since we don't have GPU
  temperature: 0.5
  max_tokens: 1024
  prompt_template: "rag_with_sources"

# Logging settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/sophos_rag.log"

# API settings
api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  cors_origins: ["*"] 